#!/bin/bash
mypath=`pwd`

cd ../bml
#./example_build_gnu_openblass.sh
./example_build_gnu_essl_magma.sh
cd build; make -j; make install
cd $mypath
cd ../qmd-progress
#./example_build_gnu_openblass.sh
./example_build_gnu_essl_mgma.sh 
cd build; make -j; make install
cd $mypath; cd ../LATTE
make clean 
make lammps 

