#!/bin/tcsh
##### These lines are for Moab
#  predict the duration of the job
#MSUB -l walltime=16:00:00
#
#  request resources:  two nodes
#  with 4 PEs each
#MSUB -l nodes=1:ppn=16
#

module load pgi
setenv OMP_NUM_THREADS 16
./LATTE_DOUBLE >> NM_therm.dat


