


#
# Compilation and link flags for LATTE
#

# Precision - double or single
PRECISION = DOUBLE
#PRECISION = SINGLE

# Make the latte library
# AR and RUNLIB executable default path to compile 
# latte as a library (change accordingly)
MAKELIB = ON
AR = /usr/bin/ar cq
RANLIB = /usr/bin/ranlib
MY_PATH=$(shell pwd)

# Use PROGRESS and BML libraries
PROGRESS = ON
GRAPH = OFF
LPROGRESS_PATH=${PROGRESS_PATH}
LBML_PATH=${BML_PATH}
LMAGMA_PATH=${MAGMA_PATH}
LMETIS_PATH=${METIS_PATH}
LOPENBLAS_PATH=${OPENBLAS_PATH}
LCUDA_PATH=${CUDA_PATH}

# Use METIS library for graph partitioning
METIS = OFF

# GPU available - OFF or ON
GPUOPT = OFF

# Using DBCSR library from cp2k? OFF or ON
DBCSR_OPT = OFF

# Parallelizing over k-points?
MPIOPT = OFF

#
# CPU Fortran options
#

FC = gfortran
FCL = $(FC)

FFLAGS =  -ffree-line-length-none -fopenmp -lpthread -Wmissing-include-dirs 
FFLAGS += -O2 -g -DNDEBUG -fopenmp -fopenmp 
FFLAGS += -I$(LPROGRESS_PATH)/include -I$(LBML_PATH)/include
FFLAGS += -ffree-line-length-none  -O2 -g -DNDEBUG -fopenmp -fopenmp
LINKFLAG = $(FFLAGS)



LIB = -fopenmp -lpthread -L$(LOPENBLAS_PATH)/lib -lopenblas
LIB += -L$(LCUDA_PATH)/lib -lcublas
LIB += -L$(LMAGMA_PATH)/lib -lmagma
LIB  += -L$(LPROGRESS_PATH)/lib -lprogress -L$(LBML_PATH)/lib -lbml_fortran -lbml
LIB += -fopenmp -L$(LMAGMA_PATH)/lib  -lmagma -L$(LCUDA_PATH)/lib -lcublas -lcusolver
LIB += -lm -lgfortran
LIB += -fopenmp -lpthread -L$(LOPENBLAS_PATH)/lib -lopenblas
LIB += $(FFLAGS)

# Uncomment for coverage
#CVR = OFF
ifeq ($(CVR), ON)
  FFLAGS += -fprofile-arcs -ftest-coverage
  LINKFLAG += -fprofile-arcs -ftest-coverage
endif

ifeq ($(PROGRESS), ON)
  LIB += -L$(LPROGRESS_PATH)/lib -lprogress -L$(LBML_PATH)/lib -lbml_fortran -lbml
  FFLAGS += -I$(LBML_PATH)/include -I$(LPROGRESS_PATH)/include
endif

ifeq ($(GRAPH), ON)
  LIB += -L$(LMETIS_PATH)/lib -lmetis
  FFLAGS += -I$(LMETIS_PATH)/include
endif

#
# GPU options
#

GPU_CUDA_LIB = -L${LCUDA_PATH}/lib64/ -lcublas -lcudart

GPU_ARCH = sm_86

