SUBROUTINE GETCORRS

  USE CONSTANTS_MOD
  USE SETUPARRAY
  USE UNIVARRAY
  USE KSPACEARRAY
  USE NONOARRAY
  USE SPINARRAY
  USE PPOTARRAY
  USE COULOMBARRAY
  USE DIAGARRAY
  USE NEBLISTARRAY
  USE VIRIALARRAY
  USE MYPRECISION
  
  IMPLICIT NONE

  INTEGER :: I, J, K, NREF, N, NATSMAX, II, JJ, NACC
  INTEGER :: DOBI, DOPP, INTID, PPID, PPPARAM
  INTEGER, ALLOCATABLE :: NATSREF(:), CHARGEREF(:), KPOINTREF(:,:)
  INTEGER :: N_C, N_H, N_N, N_O, N_U, N_W, N_FE, N_CR, N_NI, N_PU
  REAL(LATTEPREC), ALLOCATABLE :: XREF(:,:,:), FREF(:,:,:), BOXREF(:,:,:)
  REAL(LATTEPREC), ALLOCATABLE :: STRESSREF(:,:,:), ENERGYREF(:), DIPOLEREF(:)
  REAL(LATTEPREC), ALLOCATABLE :: GAPREF(:)
  REAL(LATTEPREC) :: KEEPINT, KEEPPPTAB, PPKEEP, TMPF, EATOM
  REAL(LATTEPREC), PARAMETER :: C_ENERGY = -1.2354D0, H_ENERGY = -0.9755D0
  REAL(LATTEPREC), PARAMETER :: N_ENERGY = -3.1225D0!, U_ENERGY = -2.8400D0
  REAL(LATTEPREC), PARAMETER :: O_ENERGY = -1.5130D0
!  REAL(LATTEPREC), PARAMETER :: C_ENERGY = -1.2362D0, H_ENERGY = -1.1170D0
!  REAL(LATTEPREC), PARAMETER :: N_ENERGY = -3.1204D0!, U_ENERGY = -2.8400D0
!  REAL(LATTEPREC), PARAMETER :: O_ENERGY = -1.5153D0
  REAL(LATTEPREC), PARAMETER :: W_ENERGY = 0.0D0
  REAL(LATTEPREC), PARAMETER :: FE_ENERGY = 0.0D0, CR_ENERGY = 0.0D0
  REAL(LATTEPREC), PARAMETER :: NI_ENERGY = 0.0D0
  REAL(LATTEPREC), PARAMETER :: U_ENERGY = 0.0D0!, O_ENERGY = 0.0D0
  REAL(LATTEPREC), PARAMETER :: PU_ENERGY = -4.41D0
  REAL(LATTEPREC) :: MYENERGY, FORCE_ERROR, JUNK
  CHARACTER(LEN=2), ALLOCATABLE :: SPECREF(:,:)
  CHARACTER(LEN=2) :: TMPSPEC

  OPEN(UNIT=40, STATUS="OLD", FILE="Yang.ref")
  OPEN(UNIT=70, STATUS="NEW", FILE="QM9_energy.dat")

  NATSMAX = 0
  READ(40,*) NREF
  DO I = 1, NREF

     READ(40,*) N

     IF (N .GT. NATSMAX) NATSMAX = N

     READ(40,*) JUNK, JUNK, JUNK
     READ(40,*) JUNK, JUNK, JUNK
     READ(40,*) JUNK, JUNK, JUNK
     DO J = 1, N
        READ(40,*) TMPSPEC, JUNK, JUNK, JUNK
     ENDDO
     READ(40,*) JUNK
     DO J = 1, N
        READ(40,*) JUNK, JUNK, JUNK
     ENDDO
!     READ(40,*) JUNK, JUNK, JUNK
!     READ(40,*) JUNK, JUNK, JUNK
!     READ(40,*) JUNK, JUNK, JUNK
     
     READ(40,*) JUNK
     READ(40,*) JUNK
!     READ(40,*) K, K, K
  ENDDO

  REWIND(40)

  ALLOCATE(XREF(3,NATSMAX,NREF), FREF(3,NATSMAX,NREF), BOXREF(3,3,NREF), SPECREF(NATSMAX, NREF))
  ALLOCATE(STRESSREF(3,3,NREF), ENERGYREF(NREF), NATSREF(NREF), CHARGEREF(NREF))
  ALLOCATE(GAPREF(NREF), DIPOLEREF(NREF))

  READ(40,*) NREF
  DO I = 1, NREF
     
     READ(40,*) NATSREF(I)

     READ(40,*) BOXREF(1,1,I), BOXREF(1,2,I), BOXREF(1,3,I)
     READ(40,*) BOXREF(2,1,I), BOXREF(2,2,I), BOXREF(2,3,I)
     READ(40,*) BOXREF(3,1,I), BOXREF(3,2,I), BOXREF(3,3,I)
     
     DO J = 1, NATSREF(I)

        READ(40,*) SPECREF(J,I), XREF(1,J,I), XREF(2,J,I), XREF(3,J,I)
        
     ENDDO

     READ(40,*) ENERGYREF(I)

     DO J = 1, NATSREF(I)

        READ(40,*) FREF(1,J,I), FREF(2,J,I), FREF(3,J,I)

     ENDDO

!     READ(40,*) STRESSREF(1,1,I), STRESSREF(1,2,I), STRESSREF(1,3,I)
!     READ(40,*) STRESSREF(2,1,I), STRESSREF(2,2,I), STRESSREF(2,3,I)
!     READ(40,*) STRESSREF(3,1,I), STRESSREF(3,2,I), STRESSREF(3,3,I)

!     READ(40,*) CHARGEREF(I)
     READ(40,*) DIPOLEREF(I)
     READ(40,*) GAPREF(I)

!     READ(40,*) KPOINTREF(1,I), KPOINTREF(2,I), KPOINTREF(3,I)

  ENDDO

  CLOSE(40)

  DO JJ = 1, NREF ! Begin the loop over all the reference molecules/structures

     !         PRINt*, JJ

        ! Deallocate the arrays

     DEALLOCATE(CR, F, FTOT, FPP, ATELE, DELTAQ, MYCHARGE, ELEMPOINTER)
     IF (ALLOCATED(ORBITAL_LIST)) DEALLOCATE(ORBITAL_LIST)
     IF (ALLOCATED(H_ONSITE)) DEALLOCATE(H_ONSITE)
     IF (ALLOCATED(IGL_MAP)) DEALLOCATE(IGL_MAP)
     IF (ALLOCATED(CUTOFF_LIST)) DEALLOCATE(CUTOFF_LIST)
     
     IF (ELECTRO .EQ. 0) DEALLOCATE(LCNSHIFT)
     IF (KON .EQ. 1) DEALLOCATE(KF)

     IF (BASISTYPE .EQ. "NONORTHO") THEN
        IF (ALLOCATED(FPUL)) DEALLOCATE(FPUL)
     !   IF (ALLOCATED(FSLCN)) DEALLOCATE(FSLCN)
     !   IF (ALLOCATED(FSCOUL)) DEALLOCATE(FSCOUL)
     !   IF (ALLOCATED(FSSPIN)) DEALLOCATE(FSSPIN)
     ENDIF
           
        ! Add the reference structure to the arrays LATTE uses for calculations

        ! Allocate first

     NATS = NATSREF(JJ)
     
     ALLOCATE(CR(3,NATS), ATELE(NATS), F(3,NATS), &
             FPP(3,NATS), FTOT(3,NATS))
     ALLOCATE(DELTAQ(NATS), MYCHARGE(NATS))
     ALLOCATE(ELEMPOINTER(NATS))
     
     IF (ELECTRO .EQ. 0) THEN
        ALLOCATE(LCNSHIFT(NATS))
        LCNSHIFT = ZERO
     ENDIF
        
     IF (KON .EQ. 1) ALLOCATE(KF(3,NATS))
     
     DO I = 1, NATS
        CR(1,I) = XREF(1,I,JJ)
        CR(2,I) = XREF(2,I,JJ)
        CR(3,I) = XREF(3,I,JJ)
        ATELE(I) = SPECREF(I,JJ)
     ENDDO
     
     BOX = BOXREF(:,:,JJ)

!     CHARGE = CHARGEREF(JJ)

!     NKX = KPOINTREF(1,JJ)
!     NKY = KPOINTREF(2,JJ)
!     NKZ = KPOINTREF(3,JJ)
     
!        NKTOT = NKX*NKY*NKZ

     DO I = 1, NATS
        DO J = 1, NOELEM
           IF (ATELE(I) .EQ. ELE(J)) ELEMPOINTER(I) = J
        ENDDO
     ENDDO
     
     IF (BASISTYPE .EQ. "NONORTHO")  ALLOCATE(FPUL(3,NATS))
     
     IF (ALLOCATED(H)) DEALLOCATE(H)
     IF (ALLOCATED(HDIAG)) DEALLOCATE(HDIAG)
     IF (ALLOCATED(HK)) DEALLOCATE(HK)
     IF (ALLOCATED(HKDIAG)) DEALLOCATE(HKDIAG)
     IF (ALLOCATED(QLIST)) DEALLOCATE(QLIST)
     IF (ALLOCATED(H0)) DEALLOCATE(H0)
     IF (ALLOCATED(HK0)) DEALLOCATE(HK0)
     IF (ALLOCATED(BO)) DEALLOCATE(BO)
     IF (ALLOCATED(KBO)) DEALLOCATE(KBO)
     IF (ALLOCATED(HUP)) DEALLOCATE(HUP)
     IF (ALLOCATED(HDOWN)) DEALLOCATE(HDOWN)
     IF (ALLOCATED(RHOUP)) DEALLOCATE(RHOUP)
     IF (ALLOCATED(RHODOWN)) DEALLOCATE(RHODOWN)
     IF (ALLOCATED(H2VECT)) DEALLOCATE(H2VECT)
     IF (ALLOCATED(KHUP)) DEALLOCATE(KHUP)
     IF (ALLOCATED(KHDOWN)) DEALLOCATE(KHDOWN)
     IF (ALLOCATED(KRHOUP)) DEALLOCATE(KRHOUP)
     IF (ALLOCATED(KRHODOWN)) DEALLOCATE(KRHODOWN)
     IF (ALLOCATED(SPINLIST)) DEALLOCATE(SPINLIST)
     IF (ALLOCATED(ZSPINLIST)) DEALLOCATE(ZSPINLIST)
     IF (ALLOCATED(DELTASPIN)) DEALLOCATE(DELTASPIN)
     IF (ALLOCATED(OLDDELTASPIN)) DEALLOCATE(OLDDELTASPIN)
     
     CALL GETHDIM
     
     IF (ALLOCATED(MATINDLIST)) DEALLOCATE(MATINDLIST)
     IF (ALLOCATED(SPININDLIST)) DEALLOCATE(SPININDLIST)
     
     CALL GETMATINDLIST
     
     IF (ALLOCATED(BOZERO)) DEALLOCATE(BOZERO)
     IF (ALLOCATED(RHOUPZERO)) DEALLOCATE(RHOUPZERO)
     IF (ALLOCATED(RHODOWNZERO)) DEALLOCATE(RHODOWNZERO)
     
     CALL RHOZERO
     
     CALL GETBNDFIL()
     
     IF (ALLOCATED(OLDDELTAQS)) DEALLOCATE(OLDDELTAQS)
     IF (ALLOCATED(COULOMBV)) DEALLOCATE(COULOMBV)
     IF (ALLOCATED(FCOUL)) DEALLOCATE(FCOUL)
     IF (ALLOCATED(SINLIST)) DEALLOCATE(SINLIST)
     IF (ALLOCATED(COSLIST)) DEALLOCATE(COSLIST)

     IF (ALLOCATED(TOTNEBTB)) DEALLOCATE(TOTNEBTB)
     IF (ALLOCATED(TOTNEBPP)) DEALLOCATE(TOTNEBPP)
     IF (ALLOCATED(TOTNEBCOUL)) DEALLOCATE(TOTNEBCOUL)
     
     CALL ALLOCATENEBARRAYS
     
     IF (ELECTRO .EQ. 1) THEN
        
        CALL ALLOCATECOULOMB
        
        CALL INITCOULOMB
        
     ENDIF
     
     IF (ALLOCATED( NONO_WORK  )) DEALLOCATE( NONO_WORK  )
     IF (ALLOCATED( NONO_IWORK  )) DEALLOCATE( NONO_IWORK  )
     IF (ALLOCATED( NONO_EVALS  )) DEALLOCATE( NONO_EVALS  )
     IF (ALLOCATED( XMAT  )) DEALLOCATE( XMAT  )
     IF (ALLOCATED( SMAT  )) DEALLOCATE( SMAT  )
     IF (ALLOCATED( NONOTMP  )) DEALLOCATE( NONOTMP  )
     IF (ALLOCATED( UMAT  )) DEALLOCATE( UMAT  )
     IF (ALLOCATED( X2HRHO  )) DEALLOCATE( X2HRHO )
     IF (ALLOCATED( HJJ  )) DEALLOCATE( HJJ  )
     IF (ALLOCATED( ORTHOH  )) DEALLOCATE( ORTHOH   )
     IF (ALLOCATED( ORTHOHUP  )) DEALLOCATE( ORTHOHUP  )
     IF (ALLOCATED( ORTHOHDOWN  )) DEALLOCATE( ORTHOHDOWN  )
     IF (ALLOCATED( SPINTMP  )) DEALLOCATE( SPINTMP  )
     IF (ALLOCATED( SH2 )) DEALLOCATE(SH2)
     IF (ALLOCATED( SK  )) DEALLOCATE( SK   )
     IF (ALLOCATED( KXMAT   )) DEALLOCATE( KXMAT  )
     IF (ALLOCATED( ZHJJ  )) DEALLOCATE( ZHJJ  )
     IF (ALLOCATED( KORTHOH  )) DEALLOCATE( KORTHOH  )
     IF (ALLOCATED( KORTHOHUP  )) DEALLOCATE( KORTHOHUP  )
     IF (ALLOCATED( KORTHOHDOWN  )) DEALLOCATE( KORTHOHDOWN  )
     
     IF (BASISTYPE .EQ. "NONORTHO") CALL ALLOCATENONO

     CALL NEBLISTS(0)

     IF (ALLOCATED(ORBITAL_LIST)) DEALLOCATE(ORBITAL_LIST)
     IF (ALLOCATED(H_ONSITE)) DEALLOCATE(H_ONSITE)
     IF (ALLOCATED(IGL_MAP)) DEALLOCATE(IGL_MAP)
     IF (ALLOCATED(CUTOFF_LIST)) DEALLOCATE(CUTOFF_LIST)

     
     CALL GENORBITALLIST
     CALL GENHONSITE
     CALL GENCUTOFFLIST
     CALL BUILD_INTEGRAL_MAP
     
     IF (KON .EQ. 0) THEN
        
        CALL BLDNEWHS
        
     ELSE
        
        CALL KBLDNEWH
        
     ENDIF
     
     IF (SPINON .EQ. 1) THEN
        
        CALL GETDELTASPIN
        
        CALL BLDSPINH
        
     ENDIF
     
     IF (ALLOCATED(DIAG_WORK)) DEALLOCATE(DIAG_WORK)
     IF (ALLOCATED(DIAG_IWORK)) DEALLOCATE(DIAG_IWORK)
     IF (ALLOCATED(DIAG_ZWORK)) DEALLOCATE(DIAG_ZWORK)
     IF (ALLOCATED(DIAG_RWORK)) DEALLOCATE(DIAG_RWORK)
     IF (ALLOCATED(ZHEEVD_WORK)) DEALLOCATE(ZHEEVD_WORK)
     IF (ALLOCATED(ZHEEVD_RWORK)) DEALLOCATE(ZHEEVD_RWORK)
     IF (ALLOCATED(ZHEEVD_IWORK)) DEALLOCATE(ZHEEVD_IWORK)
     IF (ALLOCATED(EVALS)) DEALLOCATE(EVALS)
     IF (ALLOCATED(EVECS)) DEALLOCATE(EVECS)
     IF (ALLOCATED(UPEVALS)) DEALLOCATE(UPEVALS)
     IF (ALLOCATED(UPEVECS)) DEALLOCATE(UPEVECS)
     IF (ALLOCATED(DOWNEVALS)) DEALLOCATE(DOWNEVALS)
     IF (ALLOCATED(DOWNEVECS)) DEALLOCATE(DOWNEVECS)
     IF (ALLOCATED(KEVALS)) DEALLOCATE(KEVALS)
     IF (ALLOCATED(KEVECS)) DEALLOCATE(KEVECS)
     IF (ALLOCATED(CPLIST)) DEALLOCATE(CPLIST)
     IF (ALLOCATED(KEVALSUP)) DEALLOCATE(KEVALSUP)
     IF (ALLOCATED(KEVALSDOWN)) DEALLOCATE(KEVALSDOWN)
     IF (ALLOCATED(KEVECSUP)) DEALLOCATE(KEVECSUP)
     IF (ALLOCATED(KEVECSDOWN)) DEALLOCATE(KEVECSDOWN)
     
     CALL ALLOCATEDIAG
     
     IF (ELECTRO .EQ. 0) CALL QNEUTRAL(0,1) ! Local charge neutrality           
           
     IF (ELECTRO .EQ. 1) CALL QCONSISTENCY(0,1) ! Self-consistent charges 

!     IF (COMPFORCE .EQ. 1) CALL GETFORCE

     CALL TOTENG

     ECOUL = ZERO
     IF (ELECTRO .EQ. 1) CALL GETCOULE
     
     ESPIN = ZERO
     IF (SPINON .EQ. 1) CALL GETSPINE
     
     EREP = ZERO
     IF (PPOTON .EQ. 1) CALL PAIRPOT
     
     IF (PPOTON .EQ. 2) CALL PAIRPOTTAB
     
!     MYENERGY = TRRHOH - ECOUL - ENTE + ESPIN + EREP

!     ELECTRONIC_ENERGY(JJ) = TRRHOH - ECOUL - ENTE + ESPIN 

     N_C = 0
     N_H = 0
     N_N = 0
     N_O = 0
     N_U = 0
     N_W = 0
     N_FE = 0
     N_CR = 0
     N_NI = 0
     N_PU = 0
     
     DO I = 1, NATS
        
        IF (ATELE(I) .EQ. "C") N_C = N_C + 1
        IF (ATELE(I) .EQ. "H") N_H = N_H + 1
        IF (ATELE(I) .EQ. "N") N_N = N_N + 1
        IF (ATELE(I) .EQ. "O") N_O = N_O + 1
        IF (ATELE(I) .EQ. "U") N_U = N_U + 1
        IF (ATELE(I) .EQ. "W") N_W = N_W + 1
        IF (ATELE(I) .EQ. "Fe") N_FE = N_FE + 1
        IF (ATELE(I) .EQ. "Cr") N_CR = N_CR + 1
        IF (ATELE(I) .EQ. "Ni") N_NI = N_NI + 1
        IF (ATELE(I) .EQ. "Pu") N_PU = N_PU + 1

     ENDDO
     
     EATOM = REAL(N_C)*C_ENERGY + REAL(N_H)*H_ENERGY + &
          REAL(N_N)*N_ENERGY + REAL(N_O)*O_ENERGY + &
          REAL(N_U)*U_ENERGY + REAL(N_FE)*FE_ENERGY + &
          REAL(N_CR)*CR_ENERGY + REAL(N_NI)*NI_ENERGY + &
          REAL(N_W)*W_ENERGY + REAL(N_PU)*PU_ENERGY
     

     MYENERGY = TRRHOH - ECOUL - ENTE + ESPIN + EREP - EATOM
     
!     FORCE_ERROR = 0.0D0

!     DO I = 1, NATS
!        FORCE_ERROR = FORCE_ERROR + SQRT(FTOT(1,I)*FTOT(1,I) + &
!             FTOT(2,I)*FTOT(2,I) + FTOT(3,I)*FTOT(3,I))
!     ENDDO

!     FORCE_ERROR = FORCE_ERROR/REAL(NATS)

     WRITE(70,10) ENERGYREF(JJ)/REAL(NATS), MYENERGY/REAL(NATS)

     
  ENDDO

10 FORMAT(2F12.6)

  RETURN
  
END SUBROUTINE GETCORRS
